### ISSUE TITLE
Add support for non premium users

### ISSUE THREAD

**Issue by Atemu** [remixz/umi#20]
Is there any specific reason why non premium users can't use umi?

[Streamlink](https://github.com/streamlink/streamlink) and [youtube-dl](https://github.com/rg3/youtube-dl) (both locally executed clients written in Python) are able to fetch the streams without premium accounts..

**Comment by remixz** [comment]
The biggest reason is because I'm not able to show the Crunchyroll ads on Umi. If I were to make this work for free accounts, I'd see it as no different than a pirate site, as it would be subverting Crunchyroll's behaviour. Despite their site not being amazing, I still respect the company for offering anime legally with very fair conditions, and more importantly I don't want to hurt the content creators. There's no technical restriction holding back using a free account, it's purely an ethical one. I hope you can understand!
