### ISSUE TITLE
Can't join room

### ISSUE THREAD

**Issue by AlicePK** [remixz/umi#4]
Another person logged into the same account can't join the room made. We have done this a lot, but this time and one other time it just won't work. Is something up with Umi? Even the host refreshing the page shows the room unjoinable and you are booted back to the main page. We have only ever seen this twice. Any ideas?
![ecf5a53abb72f843fb38ce7824cdde30](https://user-images.githubusercontent.com/32823986/31590164-aeb031be-b1d9-11e7-85ac-cb008325a1d6.png)

**Comment by remixz** [comment]
Hi! It's been a bit since you filed this issue, so I'm guessing you either got it working, or just didn't use Umi player that time. Very understandable if the latter is the case. 😂 

In any case, I've completely rewritten how rooms work (see GH-5 for the technical work, if interested), so now rooms can no longer expire. If you have any issues with rooms in the future, definitely open up a new issue. I hope you'll give Umi another try if the time comes! 😄
